### ISSUE TITLE
为什么用不了

### ISSUE THREAD

**Issue by 2698409414** [mohuihui/DingTalk_Assistant#1]
是不支持新版本吗，提示注入成功然后没用连多开都不行

**Comment by mohuihui** [comment]
目前就实现了消息防撤回一个功能。

**Comment by mohuihui** [comment]
> 是不支持新版本吗，提示注入成功然后没用连多开都不行

目前就实现了消息防撤回一个功能。

**Comment by 2698409414** [comment]
好吧。。多开不行撤回自己的消息都撤回不了

**Comment by mohuihui** [comment]
钉钉助手程序已更新，支持最新6.x版本，下载地址：
链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 
提取码：8888

在使用过程中有任何问题可以随时联系我，谢谢！

**Comment by cai23511** [comment]
> 钉钉助手程序已更新，支持最新6.x版本，下载地址： 链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 提取码：8888
> 
> 在使用过程中有任何问题可以随时联系我，谢谢！

钉钉明明关闭了但是提示钉钉正在运行，打补丁失败
