### ISSUE TITLE
停更了吗 不能用了貌似   ver： 6.0.18-Release.6110187

### ISSUE THREAD

**Issue by leafgrey** [mohuihui/DingTalk_Assistant#12]
钉钉版本  6.0.18-Release.6110187

**Comment by sobbk** [comment]
老版本可以用  5.1.9

**Comment by stone2417** [comment]
> 老版本可以用 5.1.9

老版本老是自动升级。。。关了自动升级也没用

**Comment by mohuihui** [comment]
钉钉助手程序已更新，支持最新6.x版本，下载地址：
链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 
提取码：8888

在使用过程中有任何问题可以随时联系我，谢谢！
