### ISSUE TITLE
请问为什么我打补丁总是提示

### ISSUE THREAD

**Issue by jasonyun** [mohuihui/DingTalk_Assistant#13]
![Snipaste_2021-07-08_07-57-40](https://user-images.githubusercontent.com/738056/124842595-8a304200-dfc2-11eb-9152-24d765ca4f17.jpg)
请问为什么我打补丁总是提示

**Comment by mohuihui** [comment]
钉钉助手程序已更新，支持最新6.x版本，下载地址：
链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 
提取码：8888

在使用过程中有任何问题可以随时联系我，谢谢！

**Comment by mohuihui** [comment]
钉钉助手程序已更新，支持最新6.x版本，下载地址：
链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 
提取码：8888

在使用过程中有任何问题可以随时联系我，谢谢！

**Comment by jasonyun** [comment]
dingding老是重启

**Comment by jasonyun** [comment]
关闭
