### ISSUE TITLE
v0.2版本的DingTalk_Assistant开启后，钉钉打开2秒钟后自动退出

### ISSUE THREAD

**Issue by cai23511** [mohuihui/DingTalk_Assistant#15]
v0.2版本的DingTalk_Assistant开启后，钉钉打开2秒钟后自动退出、
系统版本：WIN10 21H1 教育版
钉钉版本：60.26- Release8160887

**Comment by mohuihui** [comment]
已更新，请下载v0.3最新版“钉钉助手”。
