### ISSUE TITLE
win 11 钉钉 7.0.0  防撤回不支持

### ISSUE THREAD

**Issue by wangyuan0217** [mohuihui/DingTalk_Assistant#25]
![image](https://user-images.githubusercontent.com/12730214/218009352-a09c1374-2925-4c99-8449-42e9fb066ae5.png)

**Comment by MysTer1ous** [comment]
> ![image](https://user-images.githubusercontent.com/12730214/218009352-a09c1374-2925-4c99-8449-42e9fb066ae5.png)

作者应该不维护了
