### ISSUE TITLE
老哥 最新版的钉钉支持吗

### ISSUE THREAD

**Issue by wyap-echo** [mohuihui/DingTalk_Assistant#3]

**Comment by mohuihui** [comment]
目前只完成了消息防撤回功能，新版应该可以支持。

**Comment by EazoonHuang** [comment]
哥，自动更新了钉钉后，最新版的钉钉好像不支持了

**Comment by mohuihui** [comment]
> 哥，自动更新了钉钉后，最新版的钉钉好像不支持了

防撤回不行了？

**Comment by EazoonHuang** [comment]
> > 哥，自动更新了钉钉后，最新版的钉钉好像不支持了
> 
> 防撤回不行了？

我这边是这样的，试了几次了，不知道其他人也一样吗

**Comment by cai23511** [comment]
我这里正常的

**Comment by YanSQgit** [comment]
老哥，最新版不行。提示文件路劲不对

**Comment by mohuihui** [comment]
钉钉助手程序已更新，支持最新6.x版本，下载地址：
链接：https://pan.baidu.com/s/1vXVhCkknbczLh574eMZtxA 
提取码：8888

在使用过程中有任何问题可以随时联系我，谢谢！
